### PR TITLE
Stress tester and cusub_print pkgs

### PR DESCRIPTION
**Pull request by flamma7**
3 stage pipeline that automates testing in the sim and in hardware. [Block diagram description of the process](https://www.draw.io/#G1_E0fHf6RGEvX-vEXf7flBp4YHtVp3-Jy). 2 big additions: the GUI in the state_machine/scripts folder and the stress_tester pkg in cusub_sim/. All python scripts have argparse to help describe and configure their functionality

Also a cusub_print pkg was created that allows us to import the printing style of the state 
machine to all python code, with or without ros.

There are also some fakehydrophones files that I worked on early that are unfinished but embedded in this branch's commits, so ignore those, I'll be pushing an official fake_hydrophones branch shortly

### CODE REVIEW

**Review by skhadem — APPROVED** [review]
Looks great to me!

**Review by APChehadi — APPROVED** [review]
Very epic

**Review by derekwright29 — APPROVED** [review]
I approve this pull request

**Comment by flamma7** [comment]
THanks Mike!

**Comment by DrYerzinia** [comment]
#blindmerge

**Pull request merged**
